print("╔════════════════════════╗")
print("║       Çizimler         ║")
print("╠════════════════════════╣")
print("║ 1-) Kare               ║")
print("║ 2-) Üçgen              ║")
print("║ 3-) Daire              ║")
print("║                        ║")
print("║                        ║")
print("║                        ║")
print("║                        ║")
print("║  0-Geri Dön            ║")
print("╚════════════════════════╝")