print("╔════════════════════════╗")
print("║     Hesap Makinesi     ║")
print("╠════════════════════════╣")
print("║ 1-) Toplama            ║")
print("║ 2-) Çıkarma            ║")
print("║ 3-) Bölme              ║")
print("║ 4-) Çarpma             ║")
print("║                        ║")
print("║                        ║")
print("║                        ║")
print("║                        ║")
print("╚════════════════════════╝")
print("Seçiminiz nedir?: ",end="")
Secim= input()
print(f"{Secim}. seçeneği seçtiniz.")
