print("╔════════════════════════╗")
print("║     Oyunlar            ║")
print("╠════════════════════════╣")
print("║ 1-) Tetris             ║")
print("║ 2-) Snake              ║")
print("║ 3-) Taş Kağıt Makas    ║")
print("║                        ║")
print("║                        ║")
print("║                        ║")
print("║                        ║")
print("║  0-Geri Dön            ║")
print("╚════════════════════════╝")